version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - esearch
  - fastapi
  - frozendict
  - maxdate
  - mindate
  - ncbi
  - pubmed
  - retmax
  - uvicorn
ignoreWords: []
import: []
